version: '3.8'

services:
  # PostgreSQL数据库服务
  postgres:
    image: postgres:14-alpine
    container_name: tsb-postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: tsb_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - tsb_network

  # 后端API服务
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: tsb-backend
    restart: always
    depends_on:
      - postgres
    environment:
      - NODE_ENV=production
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
      - DB_DATABASE=tsb_db
      - PORT=3000
      - JWT_SECRET=your_secret_key_here
      - FRONTEND_URL=http://frontend:80
    ports:
      - "3000:3000"
    networks:
      - tsb_network

  # 前端服务
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: tsb-frontend
    ports:
      - "3001:80"
    depends_on:
      - backend
    networks:
      - tsb_network
    restart: unless-stopped

networks:
  tsb_network:
    driver: bridge

volumes:
  postgres_data:
