version: '3.8'

services:
  # PostgreSQL数据库服务
  postgres:
    image: postgres:14-alpine
    container_name: tsb-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: tsb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - tsb-network
    restart: unless-stopped

  # 后端API服务
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: tsb-backend
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    environment:
      - NODE_ENV=production
      - PORT=3000
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
      - DB_DATABASE=tsb
      - DB_SYNCHRONIZE=false
      - JWT_SECRET=tsb-jwt-secret-production
      - FRONTEND_URL=http://localhost:3001
    networks:
      - tsb-network
    restart: unless-stopped

  # 前端服务
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: tsb-frontend
    ports:
      - "3001:80"
    depends_on:
      - backend
    networks:
      - tsb-network
    restart: unless-stopped

networks:
  tsb-network:
    driver: bridge

volumes:
  postgres_data:
