[build]
builder = "nixpacks"
buildCommand = "cd backend && npm run build"

[deploy]
startCommand = "cd backend && npm run start:prod"
healthcheckPath = "/api/health"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
rootDirectory = "backend"
